Added a timeout to __init__.py
Nv7-GitHub/googlesearch pull request #35
Opened 2022-06-19 23:48 UTC by Yaurrdautia

Since requests seems to have a very long time out length, we can add a timeout in order to stop requests from blocking up our code. This is especially useful when using proxies that may not respond. In my opinion, 5 seconds seems like a quite generous time to allow a request to stay going for, but that can be changed to be longer.

2023-02-16 07:48 UTC, Smyja commented
> Since requests seems to have a very long time out length, we can add a timeout in order to stop requests from blocking up our code. This is especially useful when using proxies that may not respond. In my opinion, 5 seconds seems like a quite generous time to allow a request to stay going for, but that can be changed to be longer.

hey, where do you get proxies from and does the proxies parameter accept a list?

2023-04-03 04:55 UTC, Nv7-GitHub requested changes
Thanks for the pull request!

2023-04-03 04:55 UTC, Nv7-GitHub commented on googlesearch/__init__.py
Can you add an option to change this through an optional parameter in the function call?

2023-04-03 17:51 UTC, Nv7-GitHub commented
Solved in 085e984fbbd77fe23b4bfb2cfdbb11ab0b43c1d1

2023-04-03 17:51 UTC, closed without merging