Update __init__.py
Nv7-GitHub/googlesearch pull request #75
Opened 2024-02-13 12:51 UTC by AdvancedAI-NL

I wanted to fix the problem for when the SERPs generated were less than the `num_results` specified and then the code got stuck in an infinite loop. With this new code, that shouldn't happen anymore and during my tests the code was able to keep on working as intended.

2024-02-26 04:57 UTC, Nv7-GitHub requested changes
Thank you for the PR and fixing this bug! Have some small changes but overall it looks good.

2024-02-26 04:57 UTC, Nv7-GitHub commented on googlesearch/__init__.py
> +import requests
What is the purpose of this?

2024-02-26 04:57 UTC, Nv7-GitHub commented on googlesearch/__init__.py
> +            print(f"Only {fetched_results} results found for query requiring {num_results} results. Moving on to the next query.")
Don't make a print statement

2024-02-26 16:06 UTC, AdvancedAI-NL commented
> Thank you for the PR and fixing this bug! Have some small changes but overall it looks good.

You're welcome! I made a new commit fixing the problems you pointed out. Thank you for the useful code, take care!

2024-02-29 17:36 UTC, Nv7-GitHub approved these changes
Looks good! I'll test it out over my break.

2024-07-02 18:56 UTC, merged